name: 打包条码防重工具

on:
  push:
    branches: [ "main" ]  # 当你推送到 main 分支时触发
  workflow_dispatch:      # 允许手动点击运行

jobs:
  build:
    runs-on: windows-latest  # 必须使用 Windows 环境

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 执行打包
      run: |
        # --hidden-import 确保 pynput 的 Windows 驱动被打包
        # -F 打包成单文件，-w 隐藏控制台，--collect-all 收集 pynput 所有资源
        pyinstaller --noconfirm --onefile --windowed --hidden-import="pynput.keyboard._win32" --collect-all pynput cftm.py

    - name: 上传成品
      uses: actions/upload-artifact@v4
      with:
        name: BarcodeTool-Windows
        path: dist/*.exe
